FROM node:22-alpine AS deps
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci

FROM deps AS exporter
WORKDIR /app/frontend
COPY frontend/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY static/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=exporter /app/frontend/out /usr/share/nginx/html
